config/routes.rb
Rails.application.routes.draw do
  concern :commentable do 
    resources :comments, only: %i[create destroy]
  end
  
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resource :session, only: %i[new create destroy]

    resources :users, only: %i[new create edit update]

    resources :questions, concerns: :commentable  do
      resources :answers, except: %i[new show]
    end

    resources :answers, except: %i[new show], concerns: :commentable

    namespace :admin do 
      resources :users, only: %i[index create]
    end 

    root 'pages#index'
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Commentable
  
  has_many :answers, dependent: :destroy
  belongs_to :user
  has_many :question_tags, dependent: :destroy
  has_many :tags, through: :question_tags

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }

  scope :all_by_tags, ->(tags) do
    questions = includes(:user)
    if tags
      questions = questions.joins(:tags).where(tags: tags).preload(:tags)
    else
      questions = questions.includes(:question_tags, :tags)
    end
     
    questions.order(created_at: :desc)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[show destroy edit update]
  before_action :fetch_tags, only: %i[new edit]
  def show
    @question = @question.decorate
    @answer = @question.answers.build
    @answers = @question.answers.order(created_at: :desc)
    @answers = @answers.decorate
  end

  def destroy
    @question.destroy
    flash[:success] = t('questions.destroy.success')
    redirect_to questions_path
  end

  def edit; end

  def update
    if @question.update question_params
      flash[:success] = t('questions.update.success')
      redirect_to questions_path
    else
      render :edit
    end
  end

  def index
    @pagy, @questions = pagy Question.all_by_tags(params[:tag_ids])
    @questions = @questions.decorate
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build question_params

    if @question.save
      flash[:success] = t('questions.create.success')
      redirect_to questions_path
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, tag_ids: [])
  end

  def set_question
    @question = Question.find params[:id]
  end

  def fetch_tags 
    @tags = Tag.all
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= render 'shared/errors', object: @question %>

<%= form_with model: @question do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :tags %>
    </div>

    <div class="col-sm-10">
      <%= f.collection_select :tag_ids, tags, :id, :title, {}, multiple: true,
        class: 'js-multiple-select w-100' %>
    </div>
  </div>

  <%= f.submit t('global.button.submit'), class: 'btn btn-primary' %>
<% end %>

app/views/questions/_question.html.erb
<article class="card mt-3 mb-3">
  <section class="card-header">
    <%= question.user.name_or_email %>
  </section>

  <div class="card-body">
    <h2><%= question.title %></h2>

    <section class="card-text">
      <p><%= l(question.created_at, format: :short)%></p>

      <div class="my-2">
        <%= render question.tags %>
      </div>

      <p class="my-2">
        <%= truncate strip_tags(question.body), length: 150 %>
      </p>
    </section>

    <div class="btn-group">
      <%= link_to t('global.button.show'), question_path(question), class: 'btn btn-primary rounded-0' %> 
      <%= link_to t('global.button.edit'), edit_question_path(question), class: 'btn btn-secondary' %>
      <%= button_to t('global.button.delete'), question_path(question),
      class: 'btn btn-danger rounded-0', method: :delete %>
    </div>
  </div>
</article>

app/views/questions/edit.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>


<h1 class="mb-4"><%= t '.title' %></h1>

<%= render 'form', question: @question, tags: @tags %>

app/views/questions/index.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= t('.title') %></h1>

<%= link_to t('.new'), new_question_path, class: 'btn btn-primary btn-lg mb-3' %>

<%= pagination @pagy %>

<%= render @questions %>



<%= pagination @pagy %>

app/views/questions/new.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>


<h1 class="mb-4"><%= t('questions.new.title') %></h1>

<%= render 'form', question: @question, tags: @tags %>

app/views/questions/show.html.erb
<% provide :page_title, t('menu.questions') %>
<% currently_at t('menu.questions') %>
<div class="card">
  <div class="card-body">
    <h1 class="mb-4"><%= @question.title %></h1>

    <div class="lead my-3">
      <%= sanitize @question.body %>
    </div>

    <p><%= l(@question.created_at, format: :short)%></p>

    <div class="mb-3">
      <%= @question.user.gravatar %>
      <%= @question.user.name_or_email %>
    </div>

    <div class="card">
      <div class="card-body">
        <%= render 'comments/commentable', commentable: @question, comment: @comment, 
          html_id: 'questionComments' %>
      </div>
    </div>

    <div class="border-top border-bottom py-3 mt-3">
      <div class="btn-group">
        <%= link_to t('global.button.edit'), edit_question_path(@question), class: 'btn btn-secondary rounded-0' %>
        <%= button_to t('global.button.delete'), question_path(@question),
          class: 'btn btn-danger rounded-0', method: :delete %>
      </div>
    </div>
  </div>
</div>
<!-- <div class="btn-group">
  <%= link_to t('global.button.show'), question_path(@question), class: 'btn btn-primary rounded-0' %> 
  <%= link_to t('global.button.edit'), edit_question_path(@question), class: 'btn btn-secondary' %>
  <%= button_to t('global.button.delete'), question_path(@question),
    class: 'btn btn-danger rounded-0', method: :delete %>
</div> -->

<h2 class="my-3"><%= t('.write_answer') %></h2>

<%= render 'answers/form' %>

<h2 class="my-3"><%= t('.answers') %></h2>

<%= render partial: 'answers/answer', collection: @answers, as: :answer, locals: {question: @question} %>
