config/routes.rb
Rails.application.routes.draw do
  concern :commentable do 
    resources :comments, only: %i[create destroy]
  end
  
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resource :session, only: %i[new create destroy]

    resources :users, only: %i[new create edit update]

    resources :questions, concerns: :commentable  do
      resources :answers, except: %i[new show]
    end

    resources :answers, except: %i[new show], concerns: :commentable

    namespace :admin do 
      resources :users, only: %i[index create]
    end 

    root 'pages#index'
  end
end

app/views/shared/_errors.html.erb
<% if object&.errors&.full_messages&.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><%= nav_tab t('menu.home'), root_path, class: 'nav-link px-2',
              current_page: current_page %></li>
            <li><%= nav_tab t('menu.questions'), questions_path, class: 'nav-link px-2',
              current_page: current_page %></li>    
        </ul>

        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
            <li>
              <%= current_user.gravatar %>
            </li>
            <li>              
              <%= nav_tab current_user.name_or_email, edit_user_path(current_user),
              class: 'nav-link px-2 mr-1', current_page: current_page %>
            </li>

            <li><%= button_to t('menu.log_out'), session_path,                
              class: "btn text-white px-3, padding-top: 5px", method: :delete  %></li>
            
          <% else %>
            <li><%= nav_tab t('menu.sign_up'), new_user_path, 
              class: 'nav-link px-3', current_page: current_page %></li>

            <li><%= nav_tab t('menu.log_in'), new_session_path, 
              class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>

          <% I18n.available_locales.each do |locale| %>
            <li>
              <% if I18n.locale == locale %>
                <% tag.span t(locale), class: 'nav-link px-2' %>
              <% else %>
                <%= link_to t(locale), root_path(locale: locale),
                  class: 'nav-link px-2' %>
              <% end %>
            </li>
          <% end %>
        </ul>  
      </nav>
    </div>
  </header>
<% end %>