config/routes.rb
Rails.application.routes.draw do
  concern :commentable do 
    resources :comments, only: %i[create destroy]
  end
  
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resource :session, only: %i[new create destroy]

    resources :users, only: %i[new create edit update]

    resources :questions, concerns: :commentable  do
      resources :answers, except: %i[new show]
    end

    resources :answers, except: %i[new show], concerns: :commentable

    namespace :admin do 
      resources :users, only: %i[index create]
    end 

    root 'pages#index'
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Commentable
  
  belongs_to :question
  belongs_to :user
  validates :body, presence: true, length: { minimum: 5 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question
  before_action :set_answer, except: :create

  def edit; end

  def update
    if @answer.update answer_update_params
      flash[:success] = t('answers.update.success')
      redirect_to question_path(@question, anchor: "answer-#{@answer.id}")
    else
      render :edit
    end
  end

  def create
    @answer = @question.answers.build answer_create_params
    if @answer.save
      flash[:success] = t('answers.create.success')
      redirect_to question_path(@question)
    else
      @question = @question.decorate
      @answers =  @question.answers.order created_at: :desc
      @answers = @answers.decorate
      render 'questions/show'
    end
  end

  def destroy
    @answer.destroy
    flash[:success] = 'Answer destroy!'
    redirect_to question_path(@question)
  end

  private

  def answer_create_params
    params.require(:answer).permit(:body).merge(user_id: current_user.id)
  end

  def answer_update_params
    params.require(:answer).permit(:body)
  end

  def set_question
    @question = Question.find params[:question_id]
  end

  def set_answer
    @answer = @question.answers.find params[:id]
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div class="card mb-3">
  <div class="card-body">
<%= tag.article class: 'mb-3 card border-0', id: dom_id(answer) do %>

  <div class="row g-0">
    <div class="col-sm-auto text-sm-center align-self-center">
      <%= answer.user.gravatar size: 50, css_class: 'd-block' %>
      <%= answer.user.name_or_email %>
    </div>
    <div class="col-sm">
      <div class="card-body">
        <section class="card-text mb-3">
          <div class="col-sm-9">
           <div class="mt-2 mb-2">
              <%= sanitize answer.body %>
            </div>
            
            <p>
              <%= l(answer.created_at, format: :short)%>
            </p>
          </div>
        </section>

        <div class="btn-group">
          <%= link_to t('global.button.edit'), edit_question_answer_path(question, answer),
          class: 'btn btn-primary' %>
          <%= button_to t('global.button.delete'), question_answer_path(question, answer),
          class: 'btn btn-danger rounded-0', method: :delete, confirm: 'Are you shure?' %>
        </div>
      </div>
    </div>
  </div>
  
<% end %>

<%= render 'comments/commentable', commentable: answer, comment: @comment %>
</div>
  </div>

app/views/answers/_form.html.erb
<%= render 'shared/errors', object: @answer %>

<%= form_with model: [@question, @answer] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
        <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit t('global.button.submit'), class: 'btn btn-primary' %>
<% end %>

app/views/answers/edit.html.erb
<% provide :page_title, 'Edit answer' %>
<% currently_at 'Questions' %>


<h2 class="my-3"><%= t('answers.edit.title') %></h2>

<%= render 'form' %>